// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB33sLft64avJk6B-wIorlpH7Qv3SGd6cE',
    appId: '1:4700305155:web:3ebc0127ab098c322c5b36',
    messagingSenderId: '4700305155',
    projectId: 'englitics-6a483',
    authDomain: 'englitics-6a483.firebaseapp.com',
    storageBucket: 'englitics-6a483.firebasestorage.app',
    measurementId: 'G-T69ZD8WM2H',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB2vOzUcdjztG9n3c34jFE4EsnBDFlqfPs',
    appId: '1:4700305155:android:ac96ef172983372d2c5b36',
    messagingSenderId: '4700305155',
    projectId: 'englitics-6a483',
    storageBucket: 'englitics-6a483.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAr4YXwSWhCLI2CFgnEf1nu8PGSSidHrCE',
    appId: '1:4700305155:ios:64918e8d8c4b2cb22c5b36',
    messagingSenderId: '4700305155',
    projectId: 'englitics-6a483',
    storageBucket: 'englitics-6a483.firebasestorage.app',
    iosBundleId: 'com.englitics.grammar.app',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAr4YXwSWhCLI2CFgnEf1nu8PGSSidHrCE',
    appId: '1:4700305155:ios:9403ab4a3e14f24c2c5b36',
    messagingSenderId: '4700305155',
    projectId: 'englitics-6a483',
    storageBucket: 'englitics-6a483.firebasestorage.app',
    iosBundleId: 'com.example.learnEnglishApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB33sLft64avJk6B-wIorlpH7Qv3SGd6cE',
    appId: '1:4700305155:web:b4df413a6db1e5cf2c5b36',
    messagingSenderId: '4700305155',
    projectId: 'englitics-6a483',
    authDomain: 'englitics-6a483.firebaseapp.com',
    storageBucket: 'englitics-6a483.firebasestorage.app',
    measurementId: 'G-MJMJR1GDT2',
  );
}
