import 'package:flutter_riverpod/flutter_riverpod.dart';
import '../game_enums.dart';
import '../game_models.dart';

/// Provider for the professional game data repository
final professionalGameDataProvider = Provider<ProfessionalGameDataRepository>(
  (ref) => ProfessionalGameDataRepository(),
);

/// Professional game data repository for managing vocabulary data
class ProfessionalGameDataRepository {
  /// Get levels for a specific difficulty
  Future<List<GameLevel>> getLevelsForDifficulty(
      DifficultyLevel difficulty) async {
    // Simulate network delay
    await Future.delayed(const Duration(milliseconds: 500));

    switch (difficulty) {
      case DifficultyLevel.beginner:
        return _createBeginnerLevels();
      case DifficultyLevel.intermediate:
        return _createIntermediateLevels();
      case DifficultyLevel.advanced:
        return _createAdvancedLevels();
      case DifficultyLevel.expert:
        return _createExpertLevels();
    }
  }

  /// Create beginner level data
  List<GameLevel> _createBeginnerLevels() {
    return [
      GameLevel(
        id: 'beginner_1',
        title: 'Temel Kelimeler',
        description: 'Günlük hayatın temel kelimeleri',
        difficulty: DifficultyLevel.beginner,
        isUnlocked: true,
        exercises: [
          GameExercise(
            id: 'beg_ex_1',
            levelId: 'beginner_1',
            order: 1,
            title: 'Renkler',
            description: 'Temel renk isimleri',
            difficulty: DifficultyLevel.beginner,
            studyTimeSeconds: 20,
            recallTimeSeconds: 40,
            words: [
              VocabularyWord(
                id: 'color_1',
                english: 'red',
                turkish: 'kırmızı',
                phonetic: '/red/',
                category: 'colors',
                difficulty: DifficultyLevel.beginner,
                hint: 'Kan ve gül rengi',
                example: 'The apple is red.',
              ),
              VocabularyWord(
                id: 'color_2',
                english: 'blue',
                turkish: 'mavi',
                phonetic: '/bluː/',
                category: 'colors',
                difficulty: DifficultyLevel.beginner,
                hint: 'Gökyüzü rengi',
                example: 'The sky is blue.',
              ),
              VocabularyWord(
                id: 'color_3',
                english: 'green',
                turkish: 'yeşil',
                phonetic: '/ɡriːn/',
                category: 'colors',
                difficulty: DifficultyLevel.beginner,
                hint: 'Ağaçların yaprak rengi',
                example: 'Grass is green.',
              ),
              VocabularyWord(
                id: 'color_4',
                english: 'yellow',
                turkish: 'sarı',
                phonetic: '/ˈjɛloʊ/',
                category: 'colors',
                difficulty: DifficultyLevel.beginner,
                hint: 'Güneş rengi',
                example: 'The sun is yellow.',
              ),
              VocabularyWord(
                id: 'color_5',
                english: 'black',
                turkish: 'siyah',
                phonetic: '/blæk/',
                category: 'colors',
                difficulty: DifficultyLevel.beginner,
                hint: 'Gecenin rengi',
                example: 'The cat is black.',
              ),
            ],
          ),
          GameExercise(
            id: 'beg_ex_2',
            levelId: 'beginner_1',
            order: 2,
            title: 'Aile',
            description: 'Aile üyeleri',
            difficulty: DifficultyLevel.beginner,
            studyTimeSeconds: 25,
            recallTimeSeconds: 45,
            words: [
              VocabularyWord(
                id: 'family_1',
                english: 'mother',
                turkish: 'anne',
                phonetic: '/ˈmʌðər/',
                category: 'family',
                difficulty: DifficultyLevel.beginner,
                hint: 'Kadın ebeveyn',
                example: 'My mother is kind.',
              ),
              VocabularyWord(
                id: 'family_2',
                english: 'father',
                turkish: 'baba',
                phonetic: '/ˈfɑːðər/',
                category: 'family',
                difficulty: DifficultyLevel.beginner,
                hint: 'Erkek ebeveyn',
                example: 'My father works hard.',
              ),
              VocabularyWord(
                id: 'family_3',
                english: 'brother',
                turkish: 'kardeş',
                phonetic: '/ˈbrʌðər/',
                category: 'family',
                difficulty: DifficultyLevel.beginner,
                hint: 'Erkek kardeş',
                example: 'I have one brother.',
              ),
              VocabularyWord(
                id: 'family_4',
                english: 'sister',
                turkish: 'kız kardeş',
                phonetic: '/ˈsɪstər/',
                category: 'family',
                difficulty: DifficultyLevel.beginner,
                hint: 'Kız kardeş',
                example: 'My sister is tall.',
              ),
              VocabularyWord(
                id: 'family_5',
                english: 'child',
                turkish: 'çocuk',
                phonetic: '/tʃaɪld/',
                category: 'family',
                difficulty: DifficultyLevel.beginner,
                hint: 'Küçük insan',
                example: 'The child is playing.',
              ),
            ],
          ),
          GameExercise(
            id: 'beg_ex_3',
            levelId: 'beginner_1',
            order: 3,
            title: 'Hayvanlar',
            description: 'Temel hayvan isimleri',
            difficulty: DifficultyLevel.beginner,
            studyTimeSeconds: 20,
            recallTimeSeconds: 40,
            words: [
              VocabularyWord(
                id: 'animal_1',
                english: 'cat',
                turkish: 'kedi',
                phonetic: '/kæt/',
                category: 'animals',
                difficulty: DifficultyLevel.beginner,
                hint: 'Miyavlayan ev hayvanı',
                example: 'The cat is sleeping.',
              ),
              VocabularyWord(
                id: 'animal_2',
                english: 'dog',
                turkish: 'köpek',
                phonetic: '/dɔːɡ/',
                category: 'animals',
                difficulty: DifficultyLevel.beginner,
                hint: 'Havlayan ev hayvanı',
                example: 'The dog is running.',
              ),
              VocabularyWord(
                id: 'animal_3',
                english: 'bird',
                turkish: 'kuş',
                phonetic: '/bɜːrd/',
                category: 'animals',
                difficulty: DifficultyLevel.beginner,
                hint: 'Uçan hayvan',
                example: 'The bird is singing.',
              ),
              VocabularyWord(
                id: 'animal_4',
                english: 'fish',
                turkish: 'balık',
                phonetic: '/fɪʃ/',
                category: 'animals',
                difficulty: DifficultyLevel.beginner,
                hint: 'Suda yaşar',
                example: 'The fish swims in water.',
              ),
              VocabularyWord(
                id: 'animal_5',
                english: 'horse',
                turkish: 'at',
                phonetic: '/hɔːrs/',
                category: 'animals',
                difficulty: DifficultyLevel.beginner,
                hint: 'Binilen büyük hayvan',
                example: 'The horse is fast.',
              ),
            ],
          ),
          GameExercise(
            id: 'beg_ex_4',
            levelId: 'beginner_1',
            order: 4,
            title: 'Sayılar',
            description: 'Temel sayılar',
            difficulty: DifficultyLevel.beginner,
            studyTimeSeconds: 20,
            recallTimeSeconds: 40,
            words: [
              VocabularyWord(
                id: 'number_1',
                english: 'one',
                turkish: 'bir',
                phonetic: '/wʌn/',
                category: 'numbers',
                difficulty: DifficultyLevel.beginner,
                hint: 'İlk sayı',
                example: 'I have one book.',
              ),
              VocabularyWord(
                id: 'number_2',
                english: 'two',
                turkish: 'iki',
                phonetic: '/tuː/',
                category: 'numbers',
                difficulty: DifficultyLevel.beginner,
                hint: 'Çift sayı',
                example: 'Two cats are playing.',
              ),
              VocabularyWord(
                id: 'number_3',
                english: 'three',
                turkish: 'üç',
                phonetic: '/θriː/',
                category: 'numbers',
                difficulty: DifficultyLevel.beginner,
                hint: 'Tek sayı',
                example: 'Three birds in the tree.',
              ),
              VocabularyWord(
                id: 'number_4',
                english: 'four',
                turkish: 'dört',
                phonetic: '/fɔːr/',
                category: 'numbers',
                difficulty: DifficultyLevel.beginner,
                hint: 'Çift sayı',
                example: 'Four wheels on a car.',
              ),
              VocabularyWord(
                id: 'number_5',
                english: 'five',
                turkish: 'beş',
                phonetic: '/faɪv/',
                category: 'numbers',
                difficulty: DifficultyLevel.beginner,
                hint: 'Elin parmak sayısı',
                example: 'Five fingers on my hand.',
              ),
            ],
          ),
          GameExercise(
            id: 'beg_ex_5',
            levelId: 'beginner_1',
            order: 5,
            title: 'Vücut',
            description: 'Vücut bölümleri',
            difficulty: DifficultyLevel.beginner,
            studyTimeSeconds: 25,
            recallTimeSeconds: 45,
            words: [
              VocabularyWord(
                id: 'body_1',
                english: 'head',
                turkish: 'kafa',
                phonetic: '/hed/',
                category: 'body',
                difficulty: DifficultyLevel.beginner,
                hint: 'Üst kısım',
                example: 'My head hurts.',
              ),
              VocabularyWord(
                id: 'body_2',
                english: 'hand',
                turkish: 'el',
                phonetic: '/hænd/',
                category: 'body',
                difficulty: DifficultyLevel.beginner,
                hint: 'Tutmak için kullanılır',
                example: 'Wash your hands.',
              ),
              VocabularyWord(
                id: 'body_3',
                english: 'foot',
                turkish: 'ayak',
                phonetic: '/fʊt/',
                category: 'body',
                difficulty: DifficultyLevel.beginner,
                hint: 'Yürümek için kullanılır',
                example: 'I hurt my foot.',
              ),
              VocabularyWord(
                id: 'body_4',
                english: 'eye',
                turkish: 'göz',
                phonetic: '/aɪ/',
                category: 'body',
                difficulty: DifficultyLevel.beginner,
                hint: 'Görmek için kullanılır',
                example: 'I see with my eyes.',
              ),
              VocabularyWord(
                id: 'body_5',
                english: 'ear',
                turkish: 'kulak',
                phonetic: '/ɪr/',
                category: 'body',
                difficulty: DifficultyLevel.beginner,
                hint: 'Duymak için kullanılır',
                example: 'I hear with my ears.',
              ),
            ],
          ),
        ],
      ),
    ];
  }

  /// Create intermediate level data
  List<GameLevel> _createIntermediateLevels() {
    return [
      GameLevel(
        id: 'intermediate_1',
        title: 'Orta Seviye',
        description: 'Daha karmaşık kelimeler ve kavramlar',
        difficulty: DifficultyLevel.intermediate,
        isUnlocked: false,
        exercises: [
          GameExercise(
            id: 'int_ex_1',
            levelId: 'intermediate_1',
            order: 1,
            title: 'Duygular',
            description: 'Temel duygular ve hisler',
            difficulty: DifficultyLevel.intermediate,
            studyTimeSeconds: 30,
            recallTimeSeconds: 50,
            words: [
              VocabularyWord(
                id: 'emotion_1',
                english: 'happy',
                turkish: 'mutlu',
                phonetic: '/ˈhæpi/',
                category: 'emotions',
                difficulty: DifficultyLevel.intermediate,
                hint: 'İyi hissetmek',
                example: 'I am happy today.',
              ),
              VocabularyWord(
                id: 'emotion_2',
                english: 'sad',
                turkish: 'üzgün',
                phonetic: '/sæd/',
                category: 'emotions',
                difficulty: DifficultyLevel.intermediate,
                hint: 'Kötü hissetmek',
                example: 'She looks sad.',
              ),
              VocabularyWord(
                id: 'emotion_3',
                english: 'angry',
                turkish: 'kızgın',
                phonetic: '/ˈæŋɡri/',
                category: 'emotions',
                difficulty: DifficultyLevel.intermediate,
                hint: 'Öfkeli olmak',
                example: 'He is angry at me.',
              ),
              VocabularyWord(
                id: 'emotion_4',
                english: 'excited',
                turkish: 'heyecanlı',
                phonetic: '/ɪkˈsaɪtɪd/',
                category: 'emotions',
                difficulty: DifficultyLevel.intermediate,
                hint: 'Coşkulu hissetmek',
                example: 'I am excited about the trip.',
              ),
              VocabularyWord(
                id: 'emotion_5',
                english: 'surprised',
                turkish: 'şaşırmış',
                phonetic: '/sərˈpraɪzd/',
                category: 'emotions',
                difficulty: DifficultyLevel.intermediate,
                hint: 'Beklenmeyen bir şey yaşamak',
                example: 'I was surprised by the news.',
              ),
            ],
          ),
          GameExercise(
            id: 'int_ex_2',
            levelId: 'intermediate_1',
            order: 2,
            title: 'Yiyecekler',
            description: 'Temel yiyecek ve içecekler',
            difficulty: DifficultyLevel.intermediate,
            studyTimeSeconds: 30,
            recallTimeSeconds: 50,
            words: [
              VocabularyWord(
                id: 'food_1',
                english: 'bread',
                turkish: 'ekmek',
                phonetic: '/bred/',
                category: 'food',
                difficulty: DifficultyLevel.intermediate,
                hint: 'Temel besin',
                example: 'I eat bread for breakfast.',
              ),
              VocabularyWord(
                id: 'food_2',
                english: 'water',
                turkish: 'su',
                phonetic: '/ˈwɔːtər/',
                category: 'food',
                difficulty: DifficultyLevel.intermediate,
                hint: 'Yaşam için gerekli sıvı',
                example: 'Drink more water.',
              ),
              VocabularyWord(
                id: 'food_3',
                english: 'chicken',
                turkish: 'tavuk',
                phonetic: '/ˈtʃɪkɪn/',
                category: 'food',
                difficulty: DifficultyLevel.intermediate,
                hint: 'Beyaz et',
                example: 'I like grilled chicken.',
              ),
              VocabularyWord(
                id: 'food_4',
                english: 'apple',
                turkish: 'elma',
                phonetic: '/ˈæpəl/',
                category: 'food',
                difficulty: DifficultyLevel.intermediate,
                hint: 'Kırmızı veya yeşil meyve',
                example: 'An apple a day keeps the doctor away.',
              ),
              VocabularyWord(
                id: 'food_5',
                english: 'coffee',
                turkish: 'kahve',
                phonetic: '/ˈkɔːfi/',
                category: 'food',
                difficulty: DifficultyLevel.intermediate,
                hint: 'Kahverengi içecek',
                example: 'I drink coffee every morning.',
              ),
            ],
          ),
          GameExercise(
            id: 'int_ex_3',
            levelId: 'intermediate_1',
            order: 3,
            title: 'Seyahat',
            description: 'Seyahat ve ulaşım kelimeleri',
            difficulty: DifficultyLevel.intermediate,
            studyTimeSeconds: 35,
            recallTimeSeconds: 55,
            words: [
              VocabularyWord(
                id: 'travel_1',
                english: 'airport',
                turkish: 'havalimanı',
                phonetic: '/ˈɛrpɔːrt/',
                category: 'travel',
                difficulty: DifficultyLevel.intermediate,
                hint: 'Uçakların kalkış yeri',
                example: 'We arrived at the airport early.',
              ),
              VocabularyWord(
                id: 'travel_2',
                english: 'hotel',
                turkish: 'otel',
                phonetic: '/hoʊˈtɛl/',
                category: 'travel',
                difficulty: DifficultyLevel.intermediate,
                hint: 'Konaklama yeri',
                example: 'The hotel is very comfortable.',
              ),
              VocabularyWord(
                id: 'travel_3',
                english: 'ticket',
                turkish: 'bilet',
                phonetic: '/ˈtɪkɪt/',
                category: 'travel',
                difficulty: DifficultyLevel.intermediate,
                hint: 'Seyahat için gerekli kağıt',
                example: 'I bought a train ticket.',
              ),
              VocabularyWord(
                id: 'travel_4',
                english: 'passport',
                turkish: 'pasaport',
                phonetic: '/ˈpæspɔːrt/',
                category: 'travel',
                difficulty: DifficultyLevel.intermediate,
                hint: 'Yurt dışı için gerekli belge',
                example: 'Don\'t forget your passport.',
              ),
              VocabularyWord(
                id: 'travel_5',
                english: 'vacation',
                turkish: 'tatil',
                phonetic: '/veɪˈkeɪʃən/',
                category: 'travel',
                difficulty: DifficultyLevel.intermediate,
                hint: 'Dinlenme zamanı',
                example: 'We are planning a vacation.',
              ),
            ],
          ),
          GameExercise(
            id: 'int_ex_4',
            levelId: 'intermediate_1',
            order: 4,
            title: 'İş Hayatı',
            description: 'İş ve meslek kelimeleri',
            difficulty: DifficultyLevel.intermediate,
            studyTimeSeconds: 35,
            recallTimeSeconds: 55,
            words: [
              VocabularyWord(
                id: 'work_1',
                english: 'office',
                turkish: 'ofis',
                phonetic: '/ˈɔːfɪs/',
                category: 'work',
                difficulty: DifficultyLevel.intermediate,
                hint: 'Çalışma yeri',
                example: 'I work in an office.',
              ),
              VocabularyWord(
                id: 'work_2',
                english: 'meeting',
                turkish: 'toplantı',
                phonetic: '/ˈmiːtɪŋ/',
                category: 'work',
                difficulty: DifficultyLevel.intermediate,
                hint: 'İş görüşmesi',
                example: 'The meeting starts at 9 AM.',
              ),
              VocabularyWord(
                id: 'work_3',
                english: 'computer',
                turkish: 'bilgisayar',
                phonetic: '/kəmˈpjuːtər/',
                category: 'work',
                difficulty: DifficultyLevel.intermediate,
                hint: 'Elektronik cihaz',
                example: 'I use my computer for work.',
              ),
              VocabularyWord(
                id: 'work_4',
                english: 'salary',
                turkish: 'maaş',
                phonetic: '/ˈsæləri/',
                category: 'work',
                difficulty: DifficultyLevel.intermediate,
                hint: 'Aylık ücret',
                example: 'My salary is good.',
              ),
              VocabularyWord(
                id: 'work_5',
                english: 'project',
                turkish: 'proje',
                phonetic: '/ˈprɑːdʒekt/',
                category: 'work',
                difficulty: DifficultyLevel.intermediate,
                hint: 'İş görevi',
                example: 'We finished the project on time.',
              ),
            ],
          ),
        ],
      ),
    ];
  }

  /// Create advanced level data
  List<GameLevel> _createAdvancedLevels() {
    return [
      GameLevel(
        id: 'advanced_1',
        title: 'İleri Seviye',
        description: 'Akademik ve profesyonel kelimeler',
        difficulty: DifficultyLevel.advanced,
        isUnlocked: false,
        exercises: [
          GameExercise(
            id: 'adv_ex_1',
            levelId: 'advanced_1',
            order: 1,
            title: 'Akademik',
            description: 'Akademik ve eğitim kelimeleri',
            difficulty: DifficultyLevel.advanced,
            studyTimeSeconds: 40,
            recallTimeSeconds: 60,
            words: [
              VocabularyWord(
                id: 'academic_1',
                english: 'research',
                turkish: 'araştırma',
                phonetic: '/rɪˈsɜːrtʃ/',
                category: 'academic',
                difficulty: DifficultyLevel.advanced,
                hint: 'Bilimsel çalışma',
                example: 'The research shows interesting results.',
              ),
              VocabularyWord(
                id: 'academic_2',
                english: 'analysis',
                turkish: 'analiz',
                phonetic: '/əˈnæləsɪs/',
                category: 'academic',
                difficulty: DifficultyLevel.advanced,
                hint: 'Detaylı inceleme',
                example: 'The analysis reveals important trends.',
              ),
              VocabularyWord(
                id: 'academic_3',
                english: 'hypothesis',
                turkish: 'hipotez',
                phonetic: '/haɪˈpɑːθəsɪs/',
                category: 'academic',
                difficulty: DifficultyLevel.advanced,
                hint: 'Bilimsel varsayım',
                example: 'Our hypothesis needs testing.',
              ),
              VocabularyWord(
                id: 'academic_4',
                english: 'methodology',
                turkish: 'metodoloji',
                phonetic: '/ˌmeθəˈdɑːlədʒi/',
                category: 'academic',
                difficulty: DifficultyLevel.advanced,
                hint: 'Çalışma yöntemi',
                example: 'The methodology is well-designed.',
              ),
              VocabularyWord(
                id: 'academic_5',
                english: 'conclusion',
                turkish: 'sonuç',
                phonetic: '/kənˈkluːʒən/',
                category: 'academic',
                difficulty: DifficultyLevel.advanced,
                hint: 'Çalışmanın varımı',
                example: 'The conclusion supports our theory.',
              ),
            ],
          ),
          GameExercise(
            id: 'adv_ex_2',
            levelId: 'advanced_1',
            order: 2,
            title: 'Teknoloji',
            description: 'Modern teknoloji kelimeleri',
            difficulty: DifficultyLevel.advanced,
            studyTimeSeconds: 40,
            recallTimeSeconds: 60,
            words: [
              VocabularyWord(
                id: 'tech_1',
                english: 'algorithm',
                turkish: 'algoritma',
                phonetic: '/ˈælɡərɪðəm/',
                category: 'technology',
                difficulty: DifficultyLevel.advanced,
                hint: 'Bilgisayar problemi çözme yöntemi',
                example: 'The algorithm processes data efficiently.',
              ),
              VocabularyWord(
                id: 'tech_2',
                english: 'artificial intelligence',
                turkish: 'yapay zeka',
                phonetic: '/ˌɑːrtɪˌfɪʃəl ɪnˈtelɪdʒəns/',
                category: 'technology',
                difficulty: DifficultyLevel.advanced,
                hint: 'Makinelerin öğrenmesi',
                example: 'Artificial intelligence is advancing rapidly.',
              ),
              VocabularyWord(
                id: 'tech_3',
                english: 'cybersecurity',
                turkish: 'siber güvenlik',
                phonetic: '/ˈsaɪbərsɪˌkjʊrəti/',
                category: 'technology',
                difficulty: DifficultyLevel.advanced,
                hint: 'Dijital güvenlik',
                example: 'Cybersecurity is crucial for businesses.',
              ),
              VocabularyWord(
                id: 'tech_4',
                english: 'blockchain',
                turkish: 'blok zinciri',
                phonetic: '/ˈblɑːktʃeɪn/',
                category: 'technology',
                difficulty: DifficultyLevel.advanced,
                hint: 'Dağıtık veri teknolojisi',
                example: 'Blockchain technology ensures transparency.',
              ),
              VocabularyWord(
                id: 'tech_5',
                english: 'sustainability',
                turkish: 'sürdürülebilirlik',
                phonetic: '/səˌsteɪnəˈbɪləti/',
                category: 'technology',
                difficulty: DifficultyLevel.advanced,
                hint: 'Çevresel devamlılık',
                example: 'Sustainability is important for the future.',
              ),
            ],
          ),
          GameExercise(
            id: 'adv_ex_3',
            levelId: 'advanced_1',
            order: 3,
            title: 'Sağlık',
            description: 'Tıp ve sağlık kelimeleri',
            difficulty: DifficultyLevel.advanced,
            studyTimeSeconds: 45,
            recallTimeSeconds: 65,
            words: [
              VocabularyWord(
                id: 'health_1',
                english: 'diagnosis',
                turkish: 'teşhis',
                phonetic: '/ˌdaɪəɡˈnoʊsɪs/',
                category: 'health',
                difficulty: DifficultyLevel.advanced,
                hint: 'Hastalığın belirlenmesi',
                example: 'The diagnosis was confirmed by tests.',
              ),
              VocabularyWord(
                id: 'health_2',
                english: 'treatment',
                turkish: 'tedavi',
                phonetic: '/ˈtriːtmənt/',
                category: 'health',
                difficulty: DifficultyLevel.advanced,
                hint: 'İyileştirme süreci',
                example: 'The treatment was very effective.',
              ),
              VocabularyWord(
                id: 'health_3',
                english: 'prevention',
                turkish: 'önleme',
                phonetic: '/prɪˈvenʃən/',
                category: 'health',
                difficulty: DifficultyLevel.advanced,
                hint: 'Hastalıktan korunma',
                example: 'Prevention is better than cure.',
              ),
              VocabularyWord(
                id: 'health_4',
                english: 'rehabilitation',
                turkish: 'rehabilitasyon',
                phonetic: '/ˌriːhəˌbɪlɪˈteɪʃən/',
                category: 'health',
                difficulty: DifficultyLevel.advanced,
                hint: 'İyileşme süreci',
                example: 'Rehabilitation helps patients recover.',
              ),
              VocabularyWord(
                id: 'health_5',
                english: 'psychology',
                turkish: 'psikoloji',
                phonetic: '/saɪˈkɑːlədʒi/',
                category: 'health',
                difficulty: DifficultyLevel.advanced,
                hint: 'Zihin bilimi',
                example: 'Psychology studies human behavior.',
              ),
            ],
          ),
          GameExercise(
            id: 'adv_ex_4',
            levelId: 'advanced_1',
            order: 4,
            title: 'Ekonomi',
            description: 'Ekonomi ve finans kelimeleri',
            difficulty: DifficultyLevel.advanced,
            studyTimeSeconds: 45,
            recallTimeSeconds: 65,
            words: [
              VocabularyWord(
                id: 'economy_1',
                english: 'investment',
                turkish: 'yatırım',
                phonetic: '/ɪnˈvestmənt/',
                category: 'economy',
                difficulty: DifficultyLevel.advanced,
                hint: 'Para yatırma',
                example: 'Real estate is a good investment.',
              ),
              VocabularyWord(
                id: 'economy_2',
                english: 'inflation',
                turkish: 'enflasyon',
                phonetic: '/ɪnˈfleɪʃən/',
                category: 'economy',
                difficulty: DifficultyLevel.advanced,
                hint: 'Fiyat artışı',
                example: 'Inflation affects purchasing power.',
              ),
              VocabularyWord(
                id: 'economy_3',
                english: 'recession',
                turkish: 'durgunluk',
                phonetic: '/rɪˈseʃən/',
                category: 'economy',
                difficulty: DifficultyLevel.advanced,
                hint: 'Ekonomik gerileme',
                example: 'The country faced a severe recession.',
              ),
              VocabularyWord(
                id: 'economy_4',
                english: 'entrepreneurship',
                turkish: 'girişimcilik',
                phonetic: '/ˌɑːntrəprəˈnɜːrʃɪp/',
                category: 'economy',
                difficulty: DifficultyLevel.advanced,
                hint: 'İş kurma becerisi',
                example: 'Entrepreneurship drives innovation.',
              ),
              VocabularyWord(
                id: 'economy_5',
                english: 'productivity',
                turkish: 'verimlilik',
                phonetic: '/ˌproʊdʌkˈtɪvəti/',
                category: 'economy',
                difficulty: DifficultyLevel.advanced,
                hint: 'Üretkenlik',
                example: 'Technology increases productivity.',
              ),
            ],
          ),
        ],
      ),
    ];
  }

  /// Create expert level data
  List<GameLevel> _createExpertLevels() {
    return [
      GameLevel(
        id: 'expert_1',
        title: 'Uzman Seviye',
        description: 'Karmaşık akademik ve felsefi terimler',
        difficulty: DifficultyLevel.expert,
        isUnlocked: false,
        exercises: [
          GameExercise(
            id: 'exp_ex_1',
            levelId: 'expert_1',
            order: 1,
            title: 'Felsefe',
            description: 'Felsefi kavramlar ve terimler',
            difficulty: DifficultyLevel.expert,
            studyTimeSeconds: 50,
            recallTimeSeconds: 70,
            words: [
              VocabularyWord(
                id: 'philosophy_1',
                english: 'epistemology',
                turkish: 'epistemoloji',
                phonetic: '/ɪˌpɪstəˈmɑːlədʒi/',
                category: 'philosophy',
                difficulty: DifficultyLevel.expert,
                hint: 'Bilgi felsefesi',
                example: 'Epistemology studies the nature of knowledge.',
              ),
              VocabularyWord(
                id: 'philosophy_2',
                english: 'metaphysics',
                turkish: 'metafizik',
                phonetic: '/ˌmetəˈfɪzɪks/',
                category: 'philosophy',
                difficulty: DifficultyLevel.expert,
                hint: 'Varlık felsefesi',
                example: 'Metaphysics explores the nature of reality.',
              ),
              VocabularyWord(
                id: 'philosophy_3',
                english: 'phenomenology',
                turkish: 'fenomenoloji',
                phonetic: '/fəˈnɑːməˈnɑːlədʒi/',
                category: 'philosophy',
                difficulty: DifficultyLevel.expert,
                hint: 'Bilinç deneyimi felsefesi',
                example: 'Phenomenology studies conscious experience.',
              ),
              VocabularyWord(
                id: 'philosophy_4',
                english: 'existentialism',
                turkish: 'varoluşçuluk',
                phonetic: '/ˌeɡzɪˈstenʃəlɪzəm/',
                category: 'philosophy',
                difficulty: DifficultyLevel.expert,
                hint: 'Varoluş felsefesi',
                example: 'Existentialism emphasizes individual freedom.',
              ),
              VocabularyWord(
                id: 'philosophy_5',
                english: 'dialectical',
                turkish: 'diyalektik',
                phonetic: '/ˌdaɪəˈlektɪkəl/',
                category: 'philosophy',
                difficulty: DifficultyLevel.expert,
                hint: 'Karşıt görüşlerin sentezi',
                example: 'Dialectical thinking involves opposing ideas.',
              ),
            ],
          ),
          GameExercise(
            id: 'exp_ex_2',
            levelId: 'expert_1',
            order: 2,
            title: 'Edebiyat',
            description: 'Edebi terimler ve analiz',
            difficulty: DifficultyLevel.expert,
            studyTimeSeconds: 50,
            recallTimeSeconds: 70,
            words: [
              VocabularyWord(
                id: 'literature_1',
                english: 'allegory',
                turkish: 'alegori',
                phonetic: '/ˈæləɡɔːri/',
                category: 'literature',
                difficulty: DifficultyLevel.expert,
                hint: 'Simgesel anlatım',
                example: 'The novel is an allegory for political power.',
              ),
              VocabularyWord(
                id: 'literature_2',
                english: 'juxtaposition',
                turkish: 'yan yana getirme',
                phonetic: '/ˌdʒʌkstəpəˈzɪʃən/',
                category: 'literature',
                difficulty: DifficultyLevel.expert,
                hint: 'Karşıtlık oluşturma',
                example: 'The juxtaposition creates dramatic contrast.',
              ),
              VocabularyWord(
                id: 'literature_3',
                english: 'synecdoche',
                turkish: 'sinekdok',
                phonetic: '/sɪˈnekdəki/',
                category: 'literature',
                difficulty: DifficultyLevel.expert,
                hint: 'Parça-bütün ilişkisi',
                example: 'Using "hands" to mean "workers" is synecdoche.',
              ),
              VocabularyWord(
                id: 'literature_4',
                english: 'catharsis',
                turkish: 'katarsis',
                phonetic: '/kəˈθɑːrsɪs/',
                category: 'literature',
                difficulty: DifficultyLevel.expert,
                hint: 'Duygusal arınma',
                example: 'Tragedy provides catharsis for the audience.',
              ),
              VocabularyWord(
                id: 'literature_5',
                english: 'verisimilitude',
                turkish: 'gerçekçilik',
                phonetic: '/ˌverəsɪˈmɪləˌtuːd/',
                category: 'literature',
                difficulty: DifficultyLevel.expert,
                hint: 'Gerçeğe benzerlik',
                example: 'The story lacks verisimilitude.',
              ),
            ],
          ),
          GameExercise(
            id: 'exp_ex_3',
            levelId: 'expert_1',
            order: 3,
            title: 'Sosyoloji',
            description: 'Toplumsal kavramlar ve teoriler',
            difficulty: DifficultyLevel.expert,
            studyTimeSeconds: 55,
            recallTimeSeconds: 75,
            words: [
              VocabularyWord(
                id: 'sociology_1',
                english: 'hegemony',
                turkish: 'hegemonya',
                phonetic: '/hɪˈdʒeməni/',
                category: 'sociology',
                difficulty: DifficultyLevel.expert,
                hint: 'Kültürel egemenlik',
                example: 'Cultural hegemony shapes social norms.',
              ),
              VocabularyWord(
                id: 'sociology_2',
                english: 'anomie',
                turkish: 'anomi',
                phonetic: '/ˈænəmi/',
                category: 'sociology',
                difficulty: DifficultyLevel.expert,
                hint: 'Toplumsal normsuzluk',
                example: 'Anomie occurs during social upheaval.',
              ),
              VocabularyWord(
                id: 'sociology_3',
                english: 'stratification',
                turkish: 'tabakalaşma',
                phonetic: '/ˌstrætəfəˈkeɪʃən/',
                category: 'sociology',
                difficulty: DifficultyLevel.expert,
                hint: 'Toplumsal sınıflandırma',
                example: 'Social stratification creates inequality.',
              ),
              VocabularyWord(
                id: 'sociology_4',
                english: 'habitus',
                turkish: 'habitus',
                phonetic: '/ˈhæbɪtəs/',
                category: 'sociology',
                difficulty: DifficultyLevel.expert,
                hint: 'Toplumsal alışkanlıklar',
                example: 'Habitus shapes our social behaviors.',
              ),
              VocabularyWord(
                id: 'sociology_5',
                english: 'intersectionality',
                turkish: 'kesişimsellik',
                phonetic: '/ˌɪntərsekʃəˈnæləti/',
                category: 'sociology',
                difficulty: DifficultyLevel.expert,
                hint: 'Çoklu kimlik deneyimi',
                example: 'Intersectionality examines overlapping identities.',
              ),
            ],
          ),
        ],
      ),
    ];
  }
}
