import 'package:flutter_riverpod/flutter_riverpod.dart';
import 'package:flutter_gen/gen_l10n/app_localizations.dart';
import '../game_enums.dart';
import '../game_models.dart';

/// Provider for the professional game data repository - needs context for localization
final professionalGameDataProvider =
    Provider.family<ProfessionalGameDataRepository, AppLocalizations>(
  (ref, l10n) => ProfessionalGameDataRepository(l10n),
);

/// Professional game data repository for managing vocabulary data
class ProfessionalGameDataRepository {
  final AppLocalizations _l10n;

  ProfessionalGameDataRepository(this._l10n);

  /// Get levels for a specific difficulty
  Future<List<GameLevel>> getLevelsForDifficulty(
      DifficultyLevel difficulty) async {
    // Simulate network delay
    await Future.delayed(const Duration(milliseconds: 500));

    switch (difficulty) {
      case DifficultyLevel.beginner:
        return _createBeginnerLevels();
      case DifficultyLevel.intermediate:
        return _createIntermediateLevels();
      case DifficultyLevel.advanced:
        return _createAdvancedLevels();
      case DifficultyLevel.expert:
        return _createExpertLevels();
    }
  }

  /// Create beginner level data
  List<GameLevel> _createBeginnerLevels() {
    return [
      GameLevel(
        id: 'beginner_1',
        title: 'basic_words',
        description: 'basic_vocabulary',
        difficulty: DifficultyLevel.beginner,
        isUnlocked: true,
        exercises: [
          GameExercise(
            id: 'beg_ex_1',
            levelId: 'beginner_1',
            order: 1,
            title: _l10n.colors,
            description: _l10n.basic_color_names,
            difficulty: DifficultyLevel.beginner,
            studyTimeSeconds: 20,
            recallTimeSeconds: 40,
            words: [
              VocabularyWord(
                id: 'color_1',
                english: 'red',
                turkish: 'kırmızı',
                phonetic: '/red/',
                category: 'colors',
                difficulty: DifficultyLevel.beginner,
                hint: 'Kan ve gül rengi',
                example: 'The apple is red.',
              ),
              VocabularyWord(
                id: 'color_2',
                english: 'blue',
                turkish: 'mavi',
                phonetic: '/bluː/',
                category: 'colors',
                difficulty: DifficultyLevel.beginner,
                hint: 'Gökyüzü rengi',
                example: 'The sky is blue.',
              ),
              VocabularyWord(
                id: 'color_3',
                english: 'green',
                turkish: 'yeşil',
                phonetic: '/ɡriːn/',
                category: 'colors',
                difficulty: DifficultyLevel.beginner,
                hint: 'Ağaçların yaprak rengi',
                example: 'Grass is green.',
              ),
              VocabularyWord(
                id: 'color_4',
                english: 'yellow',
                turkish: 'sarı',
                phonetic: '/ˈjɛloʊ/',
                category: 'colors',
                difficulty: DifficultyLevel.beginner,
                hint: 'Güneş rengi',
                example: 'The sun is yellow.',
              ),
              VocabularyWord(
                id: 'color_5',
                english: 'black',
                turkish: 'siyah',
                phonetic: '/blæk/',
                category: 'colors',
                difficulty: DifficultyLevel.beginner,
                hint: 'Gecenin rengi',
                example: 'The cat is black.',
              ),
            ],
          ),
          GameExercise(
            id: 'beg_ex_2',
            levelId: 'beginner_1',
            order: 2,
            title: _l10n.family,
            description: _l10n.family_members,
            difficulty: DifficultyLevel.beginner,
            studyTimeSeconds: 25,
            recallTimeSeconds: 45,
            words: [
              VocabularyWord(
                id: 'family_1',
                english: 'mother',
                turkish: 'anne',
                phonetic: '/ˈmʌðər/',
                category: 'family',
                difficulty: DifficultyLevel.beginner,
                hint: 'Kadın ebeveyn',
                example: 'My mother is kind.',
              ),
              VocabularyWord(
                id: 'family_2',
                english: 'father',
                turkish: 'baba',
                phonetic: '/ˈfɑːðər/',
                category: 'family',
                difficulty: DifficultyLevel.beginner,
                hint: 'Erkek ebeveyn',
                example: 'My father works hard.',
              ),
              VocabularyWord(
                id: 'family_3',
                english: 'brother',
                turkish: 'kardeş',
                phonetic: '/ˈbrʌðər/',
                category: 'family',
                difficulty: DifficultyLevel.beginner,
                hint: 'Erkek kardeş',
                example: 'I have one brother.',
              ),
              VocabularyWord(
                id: 'family_4',
                english: 'sister',
                turkish: 'kız kardeş',
                phonetic: '/ˈsɪstər/',
                category: 'family',
                difficulty: DifficultyLevel.beginner,
                hint: 'Kız kardeş',
                example: 'My sister is tall.',
              ),
              VocabularyWord(
                id: 'family_5',
                english: 'child',
                turkish: 'çocuk',
                phonetic: '/tʃaɪld/',
                category: 'family',
                difficulty: DifficultyLevel.beginner,
                hint: 'Küçük insan',
                example: 'The child is playing.',
              ),
            ],
          ),
          GameExercise(
            id: 'beg_ex_3',
            levelId: 'beginner_1',
            order: 3,
            title: _l10n.animals,
            description: _l10n.basic_animal_names,
            difficulty: DifficultyLevel.beginner,
            studyTimeSeconds: 20,
            recallTimeSeconds: 40,
            words: [
              VocabularyWord(
                id: 'animal_1',
                english: 'cat',
                turkish: 'kedi',
                phonetic: '/kæt/',
                category: 'animals',
                difficulty: DifficultyLevel.beginner,
                hint: 'Miyavlayan ev hayvanı',
                example: 'The cat is sleeping.',
              ),
              VocabularyWord(
                id: 'animal_2',
                english: 'dog',
                turkish: 'köpek',
                phonetic: '/dɔːɡ/',
                category: 'animals',
                difficulty: DifficultyLevel.beginner,
                hint: 'Havlayan ev hayvanı',
                example: 'The dog is running.',
              ),
              VocabularyWord(
                id: 'animal_3',
                english: 'bird',
                turkish: 'kuş',
                phonetic: '/bɜːrd/',
                category: 'animals',
                difficulty: DifficultyLevel.beginner,
                hint: 'Uçan hayvan',
                example: 'The bird is singing.',
              ),
              VocabularyWord(
                id: 'animal_4',
                english: 'fish',
                turkish: 'balık',
                phonetic: '/fɪʃ/',
                category: 'animals',
                difficulty: DifficultyLevel.beginner,
                hint: 'Suda yaşar',
                example: 'The fish swims in water.',
              ),
              VocabularyWord(
                id: 'animal_5',
                english: 'horse',
                turkish: 'at',
                phonetic: '/hɔːrs/',
                category: 'animals',
                difficulty: DifficultyLevel.beginner,
                hint: 'Binilen büyük hayvan',
                example: 'The horse is fast.',
              ),
            ],
          ),
          GameExercise(
            id: 'beg_ex_4',
            levelId: 'beginner_1',
            order: 4,
            title: _l10n.numbers,
            description: _l10n.basic_numbers,
            difficulty: DifficultyLevel.beginner,
            studyTimeSeconds: 20,
            recallTimeSeconds: 40,
            words: [
              VocabularyWord(
                id: 'number_1',
                english: 'one',
                turkish: 'bir',
                phonetic: '/wʌn/',
                category: 'numbers',
                difficulty: DifficultyLevel.beginner,
                hint: 'İlk sayı',
                example: 'I have one book.',
              ),
              VocabularyWord(
                id: 'number_2',
                english: 'two',
                turkish: 'iki',
                phonetic: '/tuː/',
                category: 'numbers',
                difficulty: DifficultyLevel.beginner,
                hint: 'Çift sayı',
                example: 'Two cats are playing.',
              ),
              VocabularyWord(
                id: 'number_3',
                english: 'three',
                turkish: 'üç',
                phonetic: '/θriː/',
                category: 'numbers',
                difficulty: DifficultyLevel.beginner,
                hint: 'Tek sayı',
                example: 'Three birds in the tree.',
              ),
              VocabularyWord(
                id: 'number_4',
                english: 'four',
                turkish: 'dört',
                phonetic: '/fɔːr/',
                category: 'numbers',
                difficulty: DifficultyLevel.beginner,
                hint: 'Çift sayı',
                example: 'Four wheels on a car.',
              ),
              VocabularyWord(
                id: 'number_5',
                english: 'five',
                turkish: 'beş',
                phonetic: '/faɪv/',
                category: 'numbers',
                difficulty: DifficultyLevel.beginner,
                hint: 'Elin parmak sayısı',
                example: 'Five fingers on my hand.',
              ),
            ],
          ),
          GameExercise(
            id: 'beg_ex_5',
            levelId: 'beginner_1',
            order: 5,
            title: _l10n.body,
            description: _l10n.body_parts,
            difficulty: DifficultyLevel.beginner,
            studyTimeSeconds: 25,
            recallTimeSeconds: 45,
            words: [
              VocabularyWord(
                id: 'body_1',
                english: 'head',
                turkish: 'kafa',
                phonetic: '/hed/',
                category: 'body',
                difficulty: DifficultyLevel.beginner,
                hint: 'Üst kısım',
                example: 'My head hurts.',
              ),
              VocabularyWord(
                id: 'body_2',
                english: 'hand',
                turkish: 'el',
                phonetic: '/hænd/',
                category: 'body',
                difficulty: DifficultyLevel.beginner,
                hint: 'Tutmak için kullanılır',
                example: 'Wash your hands.',
              ),
              VocabularyWord(
                id: 'body_3',
                english: 'foot',
                turkish: 'ayak',
                phonetic: '/fʊt/',
                category: 'body',
                difficulty: DifficultyLevel.beginner,
                hint: 'Yürümek için kullanılır',
                example: 'I hurt my foot.',
              ),
              VocabularyWord(
                id: 'body_4',
                english: 'eye',
                turkish: 'göz',
                phonetic: '/aɪ/',
                category: 'body',
                difficulty: DifficultyLevel.beginner,
                hint: 'Görmek için kullanılır',
                example: 'I see with my eyes.',
              ),
              VocabularyWord(
                id: 'body_5',
                english: 'ear',
                turkish: 'kulak',
                phonetic: '/ɪr/',
                category: 'body',
                difficulty: DifficultyLevel.beginner,
                hint: 'Duymak için kullanılır',
                example: 'I hear with my ears.',
              ),
            ],
          ),
          GameExercise(
            id: 'beg_ex_6',
            levelId: 'beginner_1',
            order: 6,
            title: _l10n.household_items,
            description: _l10n.basic_household_items,
            difficulty: DifficultyLevel.beginner,
            studyTimeSeconds: 20,
            recallTimeSeconds: 40,
            words: [
              VocabularyWord(
                id: 'house_1',
                english: 'table',
                turkish: 'masa',
                phonetic: '/ˈteɪbəl/',
                category: 'house',
                difficulty: DifficultyLevel.beginner,
                hint: 'Üzerine yemek konur',
                example: 'The book is on the table.',
              ),
              VocabularyWord(
                id: 'house_2',
                english: 'chair',
                turkish: 'sandalye',
                phonetic: '/tʃer/',
                category: 'house',
                difficulty: DifficultyLevel.beginner,
                hint: 'Oturmak için kullanılır',
                example: 'Sit on the chair.',
              ),
              VocabularyWord(
                id: 'house_3',
                english: 'bed',
                turkish: 'yatak',
                phonetic: '/bed/',
                category: 'house',
                difficulty: DifficultyLevel.beginner,
                hint: 'Uyumak için kullanılır',
                example: 'I sleep in my bed.',
              ),
              VocabularyWord(
                id: 'house_4',
                english: 'door',
                turkish: 'kapı',
                phonetic: '/dɔːr/',
                category: 'house',
                difficulty: DifficultyLevel.beginner,
                hint: 'Açılıp kapanır',
                example: 'Close the door please.',
              ),
              VocabularyWord(
                id: 'house_5',
                english: 'window',
                turkish: 'pencere',
                phonetic: '/ˈwɪndoʊ/',
                category: 'house',
                difficulty: DifficultyLevel.beginner,
                hint: 'Dışarıyı görmek için',
                example: 'Open the window.',
              ),
            ],
          ),
          GameExercise(
            id: 'beg_ex_7',
            levelId: 'beginner_1',
            order: 7,
            title: _l10n.clothes,
            description: _l10n.basic_clothing_items,
            difficulty: DifficultyLevel.beginner,
            studyTimeSeconds: 25,
            recallTimeSeconds: 45,
            words: [
              VocabularyWord(
                id: 'clothes_1',
                english: 'shirt',
                turkish: 'gömlek',
                phonetic: '/ʃɜːrt/',
                category: 'clothes',
                difficulty: DifficultyLevel.beginner,
                hint: 'Üst vücut giysisi',
                example: 'I wear a white shirt.',
              ),
              VocabularyWord(
                id: 'clothes_2',
                english: 'pants',
                turkish: 'pantolon',
                phonetic: '/pænts/',
                category: 'clothes',
                difficulty: DifficultyLevel.beginner,
                hint: 'Bacakları örten giysi',
                example: 'These pants are too long.',
              ),
              VocabularyWord(
                id: 'clothes_3',
                english: 'shoes',
                turkish: 'ayakkabı',
                phonetic: '/ʃuːz/',
                category: 'clothes',
                difficulty: DifficultyLevel.beginner,
                hint: 'Ayaklara giyilir',
                example: 'My shoes are comfortable.',
              ),
              VocabularyWord(
                id: 'clothes_4',
                english: 'hat',
                turkish: 'şapka',
                phonetic: '/hæt/',
                category: 'clothes',
                difficulty: DifficultyLevel.beginner,
                hint: 'Başa giyilir',
                example: 'I like your hat.',
              ),
              VocabularyWord(
                id: 'clothes_5',
                english: 'dress',
                turkish: 'elbise',
                phonetic: '/dres/',
                category: 'clothes',
                difficulty: DifficultyLevel.beginner,
                hint: 'Kadın giysisi',
                example: 'She wears a beautiful dress.',
              ),
            ],
          ),
          GameExercise(
            id: 'beg_ex_8',
            levelId: 'beginner_1',
            order: 8,
            title: 'Hava Durumu',
            description: 'Temel hava durumu kelimeleri',
            difficulty: DifficultyLevel.beginner,
            studyTimeSeconds: 20,
            recallTimeSeconds: 40,
            words: [
              VocabularyWord(
                id: 'weather_1',
                english: 'sun',
                turkish: 'güneş',
                phonetic: '/sʌn/',
                category: 'weather',
                difficulty: DifficultyLevel.beginner,
                hint: 'Gündüz ışık verir',
                example: 'The sun is bright.',
              ),
              VocabularyWord(
                id: 'weather_2',
                english: 'rain',
                turkish: 'yağmur',
                phonetic: '/reɪn/',
                category: 'weather',
                difficulty: DifficultyLevel.beginner,
                hint: 'Gökten su damlar',
                example: 'It will rain today.',
              ),
              VocabularyWord(
                id: 'weather_3',
                english: 'snow',
                turkish: 'kar',
                phonetic: '/snoʊ/',
                category: 'weather',
                difficulty: DifficultyLevel.beginner,
                hint: 'Beyaz ve soğuk',
                example: 'I love snow in winter.',
              ),
              VocabularyWord(
                id: 'weather_4',
                english: 'wind',
                turkish: 'rüzgar',
                phonetic: '/wɪnd/',
                category: 'weather',
                difficulty: DifficultyLevel.beginner,
                hint: 'Hava hareketi',
                example: 'The wind is strong.',
              ),
              VocabularyWord(
                id: 'weather_5',
                english: 'cloud',
                turkish: 'bulut',
                phonetic: '/klaʊd/',
                category: 'weather',
                difficulty: DifficultyLevel.beginner,
                hint: 'Gökyüzünde beyaz',
                example: 'Look at that cloud.',
              ),
            ],
          ),
        ],
      ),
    ];
  }

  /// Create intermediate level data
  List<GameLevel> _createIntermediateLevels() {
    return [
      GameLevel(
        id: 'intermediate_1',
        title: 'intermediate_title',
        description: 'intermediate_vocabulary',
        difficulty: DifficultyLevel.intermediate,
        isUnlocked: false,
        exercises: [
          GameExercise(
            id: 'int_ex_1',
            levelId: 'intermediate_1',
            order: 1,
            title: 'En Temel Kelimeler',
            description: 'İngilizce öğreniminde en çok kullanılan kelimeler',
            difficulty: DifficultyLevel.intermediate,
            studyTimeSeconds: 25,
            recallTimeSeconds: 50,
            words: [
              VocabularyWord(
                id: 'common_1',
                english: 'time',
                turkish: 'zaman',
                phonetic: '/taɪm/',
                category: 'common',
                difficulty: DifficultyLevel.intermediate,
                hint: 'Saatler, günler, yıllar',
                example: 'What time is it?',
              ),
              VocabularyWord(
                id: 'common_2',
                english: 'people',
                turkish: 'insanlar',
                phonetic: '/ˈpiːpəl/',
                category: 'common',
                difficulty: DifficultyLevel.intermediate,
                hint: 'İnsan topluluğu',
                example: 'Many people live here.',
              ),
              VocabularyWord(
                id: 'common_3',
                english: 'work',
                turkish: 'çalışmak',
                phonetic: '/wɜːrk/',
                category: 'common',
                difficulty: DifficultyLevel.intermediate,
                hint: 'İş yapmak',
                example: 'I work every day.',
              ),
              VocabularyWord(
                id: 'common_4',
                english: 'good',
                turkish: 'iyi',
                phonetic: '/ɡʊd/',
                category: 'common',
                difficulty: DifficultyLevel.intermediate,
                hint: 'Kaliteli, güzel',
                example: 'This is a good book.',
              ),
              VocabularyWord(
                id: 'common_5',
                english: 'know',
                turkish: 'bilmek',
                phonetic: '/noʊ/',
                category: 'common',
                difficulty: DifficultyLevel.intermediate,
                hint: 'Bilgi sahibi olmak',
                example: 'I know the answer.',
              ),
            ],
          ),
          GameExercise(
            id: 'int_ex_2',
            levelId: 'intermediate_1',
            order: 2,
            title: 'Günlük Hayat',
            description: 'Her gün kullanılan temel kelimeler',
            difficulty: DifficultyLevel.intermediate,
            studyTimeSeconds: 25,
            recallTimeSeconds: 50,
            words: [
              VocabularyWord(
                id: 'daily_1',
                english: 'home',
                turkish: 'ev',
                phonetic: '/hoʊm/',
                category: 'daily',
                difficulty: DifficultyLevel.intermediate,
                hint: 'Yaşadığımız yer',
                example: 'I am going home.',
              ),
              VocabularyWord(
                id: 'daily_2',
                english: 'school',
                turkish: 'okul',
                phonetic: '/skuːl/',
                category: 'daily',
                difficulty: DifficultyLevel.intermediate,
                hint: 'Eğitim yeri',
                example: 'Children go to school.',
              ),
              VocabularyWord(
                id: 'daily_3',
                english: 'money',
                turkish: 'para',
                phonetic: '/ˈmʌni/',
                category: 'daily',
                difficulty: DifficultyLevel.intermediate,
                hint: 'Alışveriş için kullanılan',
                example: 'I need more money.',
              ),
              VocabularyWord(
                id: 'daily_4',
                english: 'friend',
                turkish: 'arkadaş',
                phonetic: '/frend/',
                category: 'daily',
                difficulty: DifficultyLevel.intermediate,
                hint: 'Yakın kişi',
                example: 'She is my best friend.',
              ),
              VocabularyWord(
                id: 'daily_5',
                english: 'food',
                turkish: 'yemek',
                phonetic: '/fuːd/',
                category: 'daily',
                difficulty: DifficultyLevel.intermediate,
                hint: 'Beslenme için gerekli',
                example: 'I love Italian food.',
              ),
            ],
          ),
          GameExercise(
            id: 'int_ex_3',
            levelId: 'intermediate_1',
            order: 3,
            title: 'Temel Fiiller',
            description: 'En çok kullanılan eylem kelimeleri',
            difficulty: DifficultyLevel.intermediate,
            studyTimeSeconds: 25,
            recallTimeSeconds: 50,
            words: [
              VocabularyWord(
                id: 'verbs_1',
                english: 'make',
                turkish: 'yapmak',
                phonetic: '/meɪk/',
                category: 'verbs',
                difficulty: DifficultyLevel.intermediate,
                hint: 'Üretmek, oluşturmak',
                example: 'I make breakfast.',
              ),
              VocabularyWord(
                id: 'verbs_2',
                english: 'take',
                turkish: 'almak',
                phonetic: '/teɪk/',
                category: 'verbs',
                difficulty: DifficultyLevel.intermediate,
                hint: 'Bir şeyi ele geçirmek',
                example: 'Take this book.',
              ),
              VocabularyWord(
                id: 'verbs_3',
                english: 'come',
                turkish: 'gelmek',
                phonetic: '/kʌm/',
                category: 'verbs',
                difficulty: DifficultyLevel.intermediate,
                hint: 'Bir yere doğru hareket',
                example: 'Come here please.',
              ),
              VocabularyWord(
                id: 'verbs_4',
                english: 'give',
                turkish: 'vermek',
                phonetic: '/ɡɪv/',
                category: 'verbs',
                difficulty: DifficultyLevel.intermediate,
                hint: 'Birine bir şey sunmak',
                example: 'Give me the pen.',
              ),
              VocabularyWord(
                id: 'verbs_5',
                english: 'think',
                turkish: 'düşünmek',
                phonetic: '/θɪŋk/',
                category: 'verbs',
                difficulty: DifficultyLevel.intermediate,
                hint: 'Zihinsel faaliyet',
                example: 'I think you are right.',
              ),
            ],
          ),
          GameExercise(
            id: 'int_ex_4',
            levelId: 'intermediate_1',
            order: 4,
            title: 'Önemli Sıfatlar',
            description: 'En çok kullanılan tanımlayıcı kelimeler',
            difficulty: DifficultyLevel.intermediate,
            studyTimeSeconds: 25,
            recallTimeSeconds: 50,
            words: [
              VocabularyWord(
                id: 'adj_1',
                english: 'new',
                turkish: 'yeni',
                phonetic: '/nuː/',
                category: 'adjectives',
                difficulty: DifficultyLevel.intermediate,
                hint: 'Eski olmayan',
                example: 'I bought a new car.',
              ),
              VocabularyWord(
                id: 'adj_2',
                english: 'old',
                turkish: 'eski',
                phonetic: '/oʊld/',
                category: 'adjectives',
                difficulty: DifficultyLevel.intermediate,
                hint: 'Yaşlı, eskimiş',
                example: 'This is an old house.',
              ),
              VocabularyWord(
                id: 'adj_3',
                english: 'big',
                turkish: 'büyük',
                phonetic: '/bɪɡ/',
                category: 'adjectives',
                difficulty: DifficultyLevel.intermediate,
                hint: 'Küçük olmayan',
                example: 'That is a big dog.',
              ),
              VocabularyWord(
                id: 'adj_4',
                english: 'small',
                turkish: 'küçük',
                phonetic: '/smɔːl/',
                category: 'adjectives',
                difficulty: DifficultyLevel.intermediate,
                hint: 'Büyük olmayan',
                example: 'I live in a small town.',
              ),
              VocabularyWord(
                id: 'adj_5',
                english: 'right',
                turkish: 'doğru',
                phonetic: '/raɪt/',
                category: 'adjectives',
                difficulty: DifficultyLevel.intermediate,
                hint: 'Yanlış olmayan',
                example: 'You are right.',
              ),
            ],
          ),
          GameExercise(
            id: 'int_ex_5',
            levelId: 'intermediate_1',
            order: 5,
            title: 'Bağlaçlar',
            description: 'En çok kullanılan bağlantı kelimeleri',
            difficulty: DifficultyLevel.intermediate,
            studyTimeSeconds: 25,
            recallTimeSeconds: 50,
            words: [
              VocabularyWord(
                id: 'connectors_1',
                english: 'and',
                turkish: 've',
                phonetic: '/ænd/',
                category: 'connectors',
                difficulty: DifficultyLevel.intermediate,
                hint: 'Birleştirme bağlacı',
                example: 'I like tea and coffee.',
              ),
              VocabularyWord(
                id: 'connectors_2',
                english: 'but',
                turkish: 'ama',
                phonetic: '/bʌt/',
                category: 'connectors',
                difficulty: DifficultyLevel.intermediate,
                hint: 'Karşıtlık bağlacı',
                example: 'I want to go but I am busy.',
              ),
              VocabularyWord(
                id: 'connectors_3',
                english: 'because',
                turkish: 'çünkü',
                phonetic: '/bɪˈkɔːz/',
                category: 'connectors',
                difficulty: DifficultyLevel.intermediate,
                hint: 'Sebep bağlacı',
                example: 'I am happy because it is sunny.',
              ),
              VocabularyWord(
                id: 'connectors_4',
                english: 'when',
                turkish: 'ne zaman',
                phonetic: '/wen/',
                category: 'connectors',
                difficulty: DifficultyLevel.intermediate,
                hint: 'Zaman bağlacı',
                example: 'Call me when you arrive.',
              ),
              VocabularyWord(
                id: 'connectors_5',
                english: 'where',
                turkish: 'nerede',
                phonetic: '/wer/',
                category: 'connectors',
                difficulty: DifficultyLevel.intermediate,
                hint: 'Yer bağlacı',
                example: 'This is where I live.',
              ),
            ],
          ),
          GameExercise(
            id: 'int_ex_6',
            levelId: 'intermediate_1',
            order: 6,
            title: 'Soru Kelimeleri',
            description: 'En önemli soru kelimeleri',
            difficulty: DifficultyLevel.intermediate,
            studyTimeSeconds: 25,
            recallTimeSeconds: 50,
            words: [
              VocabularyWord(
                id: 'questions_1',
                english: 'what',
                turkish: 'ne',
                phonetic: '/wʌt/',
                category: 'questions',
                difficulty: DifficultyLevel.intermediate,
                hint: 'Nesne sorusu',
                example: 'What is your name?',
              ),
              VocabularyWord(
                id: 'questions_2',
                english: 'who',
                turkish: 'kim',
                phonetic: '/huː/',
                category: 'questions',
                difficulty: DifficultyLevel.intermediate,
                hint: 'Kişi sorusu',
                example: 'Who is that person?',
              ),
              VocabularyWord(
                id: 'questions_3',
                english: 'how',
                turkish: 'nasıl',
                phonetic: '/haʊ/',
                category: 'questions',
                difficulty: DifficultyLevel.intermediate,
                hint: 'Yöntem sorusu',
                example: 'How are you today?',
              ),
              VocabularyWord(
                id: 'questions_4',
                english: 'why',
                turkish: 'neden',
                phonetic: '/waɪ/',
                category: 'questions',
                difficulty: DifficultyLevel.intermediate,
                hint: 'Sebep sorusu',
                example: 'Why are you late?',
              ),
              VocabularyWord(
                id: 'questions_5',
                english: 'which',
                turkish: 'hangi',
                phonetic: '/wɪtʃ/',
                category: 'questions',
                difficulty: DifficultyLevel.intermediate,
                hint: 'Seçim sorusu',
                example: 'Which book do you prefer?',
              ),
            ],
          ),
          GameExercise(
            id: 'int_ex_7',
            levelId: 'intermediate_1',
            order: 7,
            title: 'Zaman İfadeleri',
            description: 'Günlük zaman ifadeleri',
            difficulty: DifficultyLevel.intermediate,
            studyTimeSeconds: 25,
            recallTimeSeconds: 50,
            words: [
              VocabularyWord(
                id: 'time_exp_1',
                english: 'today',
                turkish: 'bugün',
                phonetic: '/təˈdeɪ/',
                category: 'time',
                difficulty: DifficultyLevel.intermediate,
                hint: 'Bu gün',
                example: 'Today is Monday.',
              ),
              VocabularyWord(
                id: 'time_exp_2',
                english: 'tomorrow',
                turkish: 'yarın',
                phonetic: '/təˈmɔːroʊ/',
                category: 'time',
                difficulty: DifficultyLevel.intermediate,
                hint: 'Gelecek gün',
                example: 'I will see you tomorrow.',
              ),
              VocabularyWord(
                id: 'time_exp_3',
                english: 'yesterday',
                turkish: 'dün',
                phonetic: '/ˈjestərdeɪ/',
                category: 'time',
                difficulty: DifficultyLevel.intermediate,
                hint: 'Geçmiş gün',
                example: 'Yesterday was sunny.',
              ),
              VocabularyWord(
                id: 'time_exp_4',
                english: 'now',
                turkish: 'şimdi',
                phonetic: '/naʊ/',
                category: 'time',
                difficulty: DifficultyLevel.intermediate,
                hint: 'Bu an',
                example: 'I am busy now.',
              ),
              VocabularyWord(
                id: 'time_exp_5',
                english: 'later',
                turkish: 'sonra',
                phonetic: '/ˈleɪtər/',
                category: 'time',
                difficulty: DifficultyLevel.intermediate,
                hint: 'Daha sonra',
                example: 'I will call you later.',
              ),
            ],
          ),
          GameExercise(
            id: 'int_ex_8',
            levelId: 'intermediate_1',
            order: 8,
            title: 'Duygular',
            description: 'Temel duygu ifadeleri',
            difficulty: DifficultyLevel.intermediate,
            studyTimeSeconds: 25,
            recallTimeSeconds: 50,
            words: [
              VocabularyWord(
                id: 'emotions_1',
                english: 'happy',
                turkish: 'mutlu',
                phonetic: '/ˈhæpi/',
                category: 'emotions',
                difficulty: DifficultyLevel.intermediate,
                hint: 'Sevinçli hissetmek',
                example: 'I am happy to see you.',
              ),
              VocabularyWord(
                id: 'emotions_2',
                english: 'sad',
                turkish: 'üzgün',
                phonetic: '/sæd/',
                category: 'emotions',
                difficulty: DifficultyLevel.intermediate,
                hint: 'Kederli hissetmek',
                example: 'She looks sad today.',
              ),
              VocabularyWord(
                id: 'emotions_3',
                english: 'angry',
                turkish: 'kızgın',
                phonetic: '/ˈæŋɡri/',
                category: 'emotions',
                difficulty: DifficultyLevel.intermediate,
                hint: 'Öfkeli olmak',
                example: 'He is angry about the news.',
              ),
              VocabularyWord(
                id: 'emotions_4',
                english: 'tired',
                turkish: 'yorgun',
                phonetic: '/ˈtaɪərd/',
                category: 'emotions',
                difficulty: DifficultyLevel.intermediate,
                hint: 'Bitkin hissetmek',
                example: 'I am tired after work.',
              ),
              VocabularyWord(
                id: 'emotions_5',
                english: 'excited',
                turkish: 'heyecanlı',
                phonetic: '/ɪkˈsaɪtɪd/',
                category: 'emotions',
                difficulty: DifficultyLevel.intermediate,
                hint: 'Coşkulu hissetmek',
                example: 'I am excited about the trip.',
              ),
            ],
          ),
        ],
      ),
    ];
  }

  /// Create advanced level data
  List<GameLevel> _createAdvancedLevels() {
    return [
      GameLevel(
        id: 'advanced_1',
        title: 'advanced_title',
        description: 'advanced_vocabulary',
        difficulty: DifficultyLevel.advanced,
        isUnlocked: false,
        exercises: [
          GameExercise(
            id: 'adv_ex_1',
            levelId: 'advanced_1',
            order: 1,
            title: 'Önemli Kelimeler',
            description: 'İngilizce öğreniminde en çok gereken kelimeler',
            difficulty: DifficultyLevel.advanced,
            studyTimeSeconds: 30,
            recallTimeSeconds: 60,
            words: [
              VocabularyWord(
                id: 'important_1',
                english: 'important',
                turkish: 'önemli',
                phonetic: '/ɪmˈpɔːrtənt/',
                category: 'important',
                difficulty: DifficultyLevel.advanced,
                hint: 'Değerli, gerekli',
                example: 'This is very important.',
              ),
              VocabularyWord(
                id: 'important_2',
                english: 'different',
                turkish: 'farklı',
                phonetic: '/ˈdɪfərənt/',
                category: 'important',
                difficulty: DifficultyLevel.advanced,
                hint: 'Aynı olmayan',
                example: 'We have different opinions.',
              ),
              VocabularyWord(
                id: 'important_3',
                english: 'possible',
                turkish: 'mümkün',
                phonetic: '/ˈpɑːsəbəl/',
                category: 'important',
                difficulty: DifficultyLevel.advanced,
                hint: 'Yapılabilir',
                example: 'Is it possible to help?',
              ),
              VocabularyWord(
                id: 'important_4',
                english: 'problem',
                turkish: 'problem',
                phonetic: '/ˈprɑːbləm/',
                category: 'important',
                difficulty: DifficultyLevel.advanced,
                hint: 'Sorun, mesele',
                example: 'We need to solve this problem.',
              ),
              VocabularyWord(
                id: 'important_5',
                english: 'question',
                turkish: 'soru',
                phonetic: '/ˈkwestʃən/',
                category: 'important',
                difficulty: DifficultyLevel.advanced,
                hint: 'Sorulacak şey',
                example: 'I have a question for you.',
              ),
            ],
          ),
          GameExercise(
            id: 'adv_ex_2',
            levelId: 'advanced_1',
            order: 2,
            title: 'Temel Kavramlar',
            description: 'En çok kullanılan kavram kelimeleri',
            difficulty: DifficultyLevel.advanced,
            studyTimeSeconds: 30,
            recallTimeSeconds: 60,
            words: [
              VocabularyWord(
                id: 'concept_1',
                english: 'place',
                turkish: 'yer',
                phonetic: '/pleɪs/',
                category: 'concepts',
                difficulty: DifficultyLevel.advanced,
                hint: 'Konum, mekân',
                example: 'This is a beautiful place.',
              ),
              VocabularyWord(
                id: 'concept_2',
                english: 'thing',
                turkish: 'şey',
                phonetic: '/θɪŋ/',
                category: 'concepts',
                difficulty: DifficultyLevel.advanced,
                hint: 'Nesne, eşya',
                example: 'What is that thing?',
              ),
              VocabularyWord(
                id: 'concept_3',
                english: 'way',
                turkish: 'yol',
                phonetic: '/weɪ/',
                category: 'concepts',
                difficulty: DifficultyLevel.advanced,
                hint: 'Yöntem, tarz',
                example: 'This is the best way.',
              ),
              VocabularyWord(
                id: 'concept_4',
                english: 'world',
                turkish: 'dünya',
                phonetic: '/wɜːrld/',
                category: 'concepts',
                difficulty: DifficultyLevel.advanced,
                hint: 'Gezegen, evren',
                example: 'The world is beautiful.',
              ),
              VocabularyWord(
                id: 'concept_5',
                english: 'life',
                turkish: 'hayat',
                phonetic: '/laɪf/',
                category: 'concepts',
                difficulty: DifficultyLevel.advanced,
                hint: 'Yaşam, ömür',
                example: 'Life is wonderful.',
              ),
            ],
          ),
          GameExercise(
            id: 'adv_ex_3',
            levelId: 'advanced_1',
            order: 3,
            title: 'Günlük Fiiller',
            description: 'En çok gereken eylem kelimeleri',
            difficulty: DifficultyLevel.advanced,
            studyTimeSeconds: 30,
            recallTimeSeconds: 60,
            words: [
              VocabularyWord(
                id: 'daily_verbs_1',
                english: 'want',
                turkish: 'istemek',
                phonetic: '/wɑːnt/',
                category: 'verbs',
                difficulty: DifficultyLevel.advanced,
                hint: 'Arzu etmek',
                example: 'I want to learn English.',
              ),
              VocabularyWord(
                id: 'daily_verbs_2',
                english: 'need',
                turkish: 'ihtiyaç duymak',
                phonetic: '/niːd/',
                category: 'verbs',
                difficulty: DifficultyLevel.advanced,
                hint: 'Gereksinim duymak',
                example: 'I need your help.',
              ),
              VocabularyWord(
                id: 'daily_verbs_3',
                english: 'feel',
                turkish: 'hissetmek',
                phonetic: '/fiːl/',
                category: 'verbs',
                difficulty: DifficultyLevel.advanced,
                hint: 'Duygusal olarak yaşamak',
                example: 'I feel happy today.',
              ),
              VocabularyWord(
                id: 'daily_verbs_4',
                english: 'find',
                turkish: 'bulmak',
                phonetic: '/faɪnd/',
                category: 'verbs',
                difficulty: DifficultyLevel.advanced,
                hint: 'Keşfetmek, ortaya çıkarmak',
                example: 'I can\'t find my keys.',
              ),
              VocabularyWord(
                id: 'daily_verbs_5',
                english: 'help',
                turkish: 'yardım etmek',
                phonetic: '/help/',
                category: 'verbs',
                difficulty: DifficultyLevel.advanced,
                hint: 'Destek olmak',
                example: 'Can you help me?',
              ),
            ],
          ),
          GameExercise(
            id: 'adv_ex_4',
            levelId: 'advanced_1',
            order: 4,
            title: 'Zaman ve Sayılar',
            description: 'En gerekli zaman ve sayı kelimeleri',
            difficulty: DifficultyLevel.advanced,
            studyTimeSeconds: 30,
            recallTimeSeconds: 60,
            words: [
              VocabularyWord(
                id: 'time_numbers_1',
                english: 'year',
                turkish: 'yıl',
                phonetic: '/jɪr/',
                category: 'time',
                difficulty: DifficultyLevel.advanced,
                hint: '12 aylık süre',
                example: 'This year is special.',
              ),
              VocabularyWord(
                id: 'time_numbers_2',
                english: 'day',
                turkish: 'gün',
                phonetic: '/deɪ/',
                category: 'time',
                difficulty: DifficultyLevel.advanced,
                hint: '24 saatlik süre',
                example: 'Have a nice day!',
              ),
              VocabularyWord(
                id: 'time_numbers_3',
                english: 'number',
                turkish: 'sayı',
                phonetic: '/ˈnʌmbər/',
                category: 'numbers',
                difficulty: DifficultyLevel.advanced,
                hint: 'Rakam, adet',
                example: 'What is your phone number?',
              ),
              VocabularyWord(
                id: 'time_numbers_4',
                english: 'first',
                turkish: 'ilk',
                phonetic: '/fɜːrst/',
                category: 'numbers',
                difficulty: DifficultyLevel.advanced,
                hint: 'En başta olan',
                example: 'This is my first time.',
              ),
              VocabularyWord(
                id: 'time_numbers_5',
                english: 'last',
                turkish: 'son',
                phonetic: '/læst/',
                category: 'numbers',
                difficulty: DifficultyLevel.advanced,
                hint: 'En sonda olan',
                example: 'This is the last one.',
              ),
            ],
          ),
          GameExercise(
            id: 'adv_ex_5',
            levelId: 'advanced_1',
            order: 5,
            title: 'İletişim Fiilleri',
            description: 'İletişim için gerekli eylem kelimeleri',
            difficulty: DifficultyLevel.advanced,
            studyTimeSeconds: 30,
            recallTimeSeconds: 60,
            words: [
              VocabularyWord(
                id: 'communication_1',
                english: 'say',
                turkish: 'söylemek',
                phonetic: '/seɪ/',
                category: 'communication',
                difficulty: DifficultyLevel.advanced,
                hint: 'Kelime etmek',
                example: 'What did you say?',
              ),
              VocabularyWord(
                id: 'communication_2',
                english: 'tell',
                turkish: 'anlatmak',
                phonetic: '/tel/',
                category: 'communication',
                difficulty: DifficultyLevel.advanced,
                hint: 'Birine bir şey aktarmak',
                example: 'Tell me the truth.',
              ),
              VocabularyWord(
                id: 'communication_3',
                english: 'ask',
                turkish: 'sormak',
                phonetic: '/æsk/',
                category: 'communication',
                difficulty: DifficultyLevel.advanced,
                hint: 'Soru yöneltmek',
                example: 'Can I ask you something?',
              ),
              VocabularyWord(
                id: 'communication_4',
                english: 'answer',
                turkish: 'cevaplamak',
                phonetic: '/ˈænsər/',
                category: 'communication',
                difficulty: DifficultyLevel.advanced,
                hint: 'Soruya karşılık vermek',
                example: 'Please answer my question.',
              ),
              VocabularyWord(
                id: 'communication_5',
                english: 'listen',
                turkish: 'dinlemek',
                phonetic: '/ˈlɪsən/',
                category: 'communication',
                difficulty: DifficultyLevel.advanced,
                hint: 'Kulak vermek',
                example: 'Listen to me carefully.',
              ),
            ],
          ),
          GameExercise(
            id: 'adv_ex_6',
            levelId: 'advanced_1',
            order: 6,
            title: 'Hareket Fiilleri',
            description: 'Temel hareket ifadeleri',
            difficulty: DifficultyLevel.advanced,
            studyTimeSeconds: 30,
            recallTimeSeconds: 60,
            words: [
              VocabularyWord(
                id: 'movement_1',
                english: 'go',
                turkish: 'gitmek',
                phonetic: '/ɡoʊ/',
                category: 'movement',
                difficulty: DifficultyLevel.advanced,
                hint: 'Bir yere hareket etmek',
                example: 'I want to go home.',
              ),
              VocabularyWord(
                id: 'movement_2',
                english: 'come',
                turkish: 'gelmek',
                phonetic: '/kʌm/',
                category: 'movement',
                difficulty: DifficultyLevel.advanced,
                hint: 'Buraya doğru hareket',
                example: 'Come here please.',
              ),
              VocabularyWord(
                id: 'movement_3',
                english: 'walk',
                turkish: 'yürümek',
                phonetic: '/wɔːk/',
                category: 'movement',
                difficulty: DifficultyLevel.advanced,
                hint: 'Ayakla hareket etmek',
                example: 'I walk to school.',
              ),
              VocabularyWord(
                id: 'movement_4',
                english: 'run',
                turkish: 'koşmak',
                phonetic: '/rʌn/',
                category: 'movement',
                difficulty: DifficultyLevel.advanced,
                hint: 'Hızlı hareket etmek',
                example: 'I run every morning.',
              ),
              VocabularyWord(
                id: 'movement_5',
                english: 'stop',
                turkish: 'durmak',
                phonetic: '/stɑːp/',
                category: 'movement',
                difficulty: DifficultyLevel.advanced,
                hint: 'Hareketi sonlandırmak',
                example: 'Stop at the red light.',
              ),
            ],
          ),
          GameExercise(
            id: 'adv_ex_7',
            levelId: 'advanced_1',
            order: 7,
            title: 'Miktar İfadeleri',
            description: 'Miktar ve ölçü kelimeleri',
            difficulty: DifficultyLevel.advanced,
            studyTimeSeconds: 30,
            recallTimeSeconds: 60,
            words: [
              VocabularyWord(
                id: 'quantity_1',
                english: 'much',
                turkish: 'çok',
                phonetic: '/mʌtʃ/',
                category: 'quantity',
                difficulty: DifficultyLevel.advanced,
                hint: 'Büyük miktar',
                example: 'How much does it cost?',
              ),
              VocabularyWord(
                id: 'quantity_2',
                english: 'many',
                turkish: 'birçok',
                phonetic: '/ˈmeni/',
                category: 'quantity',
                difficulty: DifficultyLevel.advanced,
                hint: 'Çok sayıda',
                example: 'Many people came to the party.',
              ),
              VocabularyWord(
                id: 'quantity_3',
                english: 'some',
                turkish: 'biraz',
                phonetic: '/sʌm/',
                category: 'quantity',
                difficulty: DifficultyLevel.advanced,
                hint: 'Bir miktar',
                example: 'I need some help.',
              ),
              VocabularyWord(
                id: 'quantity_4',
                english: 'all',
                turkish: 'hepsi',
                phonetic: '/ɔːl/',
                category: 'quantity',
                difficulty: DifficultyLevel.advanced,
                hint: 'Tamamı',
                example: 'All students passed the exam.',
              ),
              VocabularyWord(
                id: 'quantity_5',
                english: 'none',
                turkish: 'hiçbiri',
                phonetic: '/nʌn/',
                category: 'quantity',
                difficulty: DifficultyLevel.advanced,
                hint: 'Sıfır miktar',
                example: 'None of them came.',
              ),
            ],
          ),
          GameExercise(
            id: 'adv_ex_8',
            levelId: 'advanced_1',
            order: 8,
            title: 'Önemli Edatlar',
            description: 'En çok kullanılan edat kelimeleri',
            difficulty: DifficultyLevel.advanced,
            studyTimeSeconds: 30,
            recallTimeSeconds: 60,
            words: [
              VocabularyWord(
                id: 'prepositions_1',
                english: 'in',
                turkish: 'içinde',
                phonetic: '/ɪn/',
                category: 'prepositions',
                difficulty: DifficultyLevel.advanced,
                hint: 'İç kısımda',
                example: 'The book is in the bag.',
              ),
              VocabularyWord(
                id: 'prepositions_2',
                english: 'on',
                turkish: 'üzerinde',
                phonetic: '/ɑːn/',
                category: 'prepositions',
                difficulty: DifficultyLevel.advanced,
                hint: 'Yüzey üstünde',
                example: 'The cup is on the table.',
              ),
              VocabularyWord(
                id: 'prepositions_3',
                english: 'at',
                turkish: 'de/da',
                phonetic: '/æt/',
                category: 'prepositions',
                difficulty: DifficultyLevel.advanced,
                hint: 'Belirli bir noktada',
                example: 'I am at school.',
              ),
              VocabularyWord(
                id: 'prepositions_4',
                english: 'with',
                turkish: 'ile',
                phonetic: '/wɪð/',
                category: 'prepositions',
                difficulty: DifficultyLevel.advanced,
                hint: 'Birlikte',
                example: 'I am with my friend.',
              ),
              VocabularyWord(
                id: 'prepositions_5',
                english: 'for',
                turkish: 'için',
                phonetic: '/fɔːr/',
                category: 'prepositions',
                difficulty: DifficultyLevel.advanced,
                hint: 'Amaç belirtir',
                example: 'This gift is for you.',
              ),
            ],
          ),
        ],
      ),
    ];
  }

  /// Create expert level data
  List<GameLevel> _createExpertLevels() {
    return [
      GameLevel(
        id: 'expert_1',
        title: 'Uzman Seviye',
        description: 'Karmaşık akademik ve felsefi terimler',
        difficulty: DifficultyLevel.expert,
        isUnlocked: false,
        exercises: [
          GameExercise(
            id: 'exp_ex_1',
            levelId: 'expert_1',
            order: 1,
            title: 'Felsefe',
            description: 'Felsefi kavramlar ve terimler',
            difficulty: DifficultyLevel.expert,
            studyTimeSeconds: 50,
            recallTimeSeconds: 70,
            words: [
              VocabularyWord(
                id: 'philosophy_1',
                english: 'epistemology',
                turkish: 'epistemoloji',
                phonetic: '/ɪˌpɪstəˈmɑːlədʒi/',
                category: 'philosophy',
                difficulty: DifficultyLevel.expert,
                hint: 'Bilgi felsefesi',
                example: 'Epistemology studies the nature of knowledge.',
              ),
              VocabularyWord(
                id: 'philosophy_2',
                english: 'metaphysics',
                turkish: 'metafizik',
                phonetic: '/ˌmetəˈfɪzɪks/',
                category: 'philosophy',
                difficulty: DifficultyLevel.expert,
                hint: 'Varlık felsefesi',
                example: 'Metaphysics explores the nature of reality.',
              ),
              VocabularyWord(
                id: 'philosophy_3',
                english: 'phenomenology',
                turkish: 'fenomenoloji',
                phonetic: '/fəˈnɑːməˈnɑːlədʒi/',
                category: 'philosophy',
                difficulty: DifficultyLevel.expert,
                hint: 'Bilinç deneyimi felsefesi',
                example: 'Phenomenology studies conscious experience.',
              ),
              VocabularyWord(
                id: 'philosophy_4',
                english: 'existentialism',
                turkish: 'varoluşçuluk',
                phonetic: '/ˌeɡzɪˈstenʃəlɪzəm/',
                category: 'philosophy',
                difficulty: DifficultyLevel.expert,
                hint: 'Varoluş felsefesi',
                example: 'Existentialism emphasizes individual freedom.',
              ),
              VocabularyWord(
                id: 'philosophy_5',
                english: 'dialectical',
                turkish: 'diyalektik',
                phonetic: '/ˌdaɪəˈlektɪkəl/',
                category: 'philosophy',
                difficulty: DifficultyLevel.expert,
                hint: 'Karşıt görüşlerin sentezi',
                example: 'Dialectical thinking involves opposing ideas.',
              ),
            ],
          ),
          GameExercise(
            id: 'exp_ex_2',
            levelId: 'expert_1',
            order: 2,
            title: 'Edebiyat',
            description: 'Edebi terimler ve analiz',
            difficulty: DifficultyLevel.expert,
            studyTimeSeconds: 50,
            recallTimeSeconds: 70,
            words: [
              VocabularyWord(
                id: 'literature_1',
                english: 'allegory',
                turkish: 'alegori',
                phonetic: '/ˈæləɡɔːri/',
                category: 'literature',
                difficulty: DifficultyLevel.expert,
                hint: 'Simgesel anlatım',
                example: 'The novel is an allegory for political power.',
              ),
              VocabularyWord(
                id: 'literature_2',
                english: 'juxtaposition',
                turkish: 'yan yana getirme',
                phonetic: '/ˌdʒʌkstəpəˈzɪʃən/',
                category: 'literature',
                difficulty: DifficultyLevel.expert,
                hint: 'Karşıtlık oluşturma',
                example: 'The juxtaposition creates dramatic contrast.',
              ),
              VocabularyWord(
                id: 'literature_3',
                english: 'synecdoche',
                turkish: 'sinekdok',
                phonetic: '/sɪˈnekdəki/',
                category: 'literature',
                difficulty: DifficultyLevel.expert,
                hint: 'Parça-bütün ilişkisi',
                example: 'Using "hands" to mean "workers" is synecdoche.',
              ),
              VocabularyWord(
                id: 'literature_4',
                english: 'catharsis',
                turkish: 'katarsis',
                phonetic: '/kəˈθɑːrsɪs/',
                category: 'literature',
                difficulty: DifficultyLevel.expert,
                hint: 'Duygusal arınma',
                example: 'Tragedy provides catharsis for the audience.',
              ),
              VocabularyWord(
                id: 'literature_5',
                english: 'verisimilitude',
                turkish: 'gerçekçilik',
                phonetic: '/ˌverəsɪˈmɪləˌtuːd/',
                category: 'literature',
                difficulty: DifficultyLevel.expert,
                hint: 'Gerçeğe benzerlik',
                example: 'The story lacks verisimilitude.',
              ),
            ],
          ),
          GameExercise(
            id: 'exp_ex_3',
            levelId: 'expert_1',
            order: 3,
            title: 'Sosyoloji',
            description: 'Toplumsal kavramlar ve teoriler',
            difficulty: DifficultyLevel.expert,
            studyTimeSeconds: 55,
            recallTimeSeconds: 75,
            words: [
              VocabularyWord(
                id: 'sociology_1',
                english: 'hegemony',
                turkish: 'hegemonya',
                phonetic: '/hɪˈdʒeməni/',
                category: 'sociology',
                difficulty: DifficultyLevel.expert,
                hint: 'Kültürel egemenlik',
                example: 'Cultural hegemony shapes social norms.',
              ),
              VocabularyWord(
                id: 'sociology_2',
                english: 'anomie',
                turkish: 'anomi',
                phonetic: '/ˈænəmi/',
                category: 'sociology',
                difficulty: DifficultyLevel.expert,
                hint: 'Toplumsal normsuzluk',
                example: 'Anomie occurs during social upheaval.',
              ),
              VocabularyWord(
                id: 'sociology_3',
                english: 'stratification',
                turkish: 'tabakalaşma',
                phonetic: '/ˌstrætəfəˈkeɪʃən/',
                category: 'sociology',
                difficulty: DifficultyLevel.expert,
                hint: 'Toplumsal sınıflandırma',
                example: 'Social stratification creates inequality.',
              ),
              VocabularyWord(
                id: 'sociology_4',
                english: 'habitus',
                turkish: 'habitus',
                phonetic: '/ˈhæbɪtəs/',
                category: 'sociology',
                difficulty: DifficultyLevel.expert,
                hint: 'Toplumsal alışkanlıklar',
                example: 'Habitus shapes our social behaviors.',
              ),
              VocabularyWord(
                id: 'sociology_5',
                english: 'intersectionality',
                turkish: 'kesişimsellik',
                phonetic: '/ˌɪntərsekʃəˈnæləti/',
                category: 'sociology',
                difficulty: DifficultyLevel.expert,
                hint: 'Çoklu kimlik deneyimi',
                example: 'Intersectionality examines overlapping identities.',
              ),
            ],
          ),
          GameExercise(
            id: 'exp_ex_4',
            levelId: 'expert_1',
            order: 4,
            title: 'Psikoloji',
            description: 'Psikolojik kavramlar ve terimler',
            difficulty: DifficultyLevel.expert,
            studyTimeSeconds: 55,
            recallTimeSeconds: 75,
            words: [
              VocabularyWord(
                id: 'psychology_1',
                english: 'consciousness',
                turkish: 'bilinç',
                phonetic: '/ˈkɑːnʃəsnəs/',
                category: 'psychology',
                difficulty: DifficultyLevel.expert,
                hint: 'Farkındalık durumu',
                example: 'Consciousness is a complex phenomenon.',
              ),
              VocabularyWord(
                id: 'psychology_2',
                english: 'subconscious',
                turkish: 'bilinçaltı',
                phonetic: '/sʌbˈkɑːnʃəs/',
                category: 'psychology',
                difficulty: DifficultyLevel.expert,
                hint: 'Farkında olmadığımız zihin',
                example: 'The subconscious affects our behavior.',
              ),
              VocabularyWord(
                id: 'psychology_3',
                english: 'cognitive',
                turkish: 'bilişsel',
                phonetic: '/ˈkɑːɡnətɪv/',
                category: 'psychology',
                difficulty: DifficultyLevel.expert,
                hint: 'Düşünce ile ilgili',
                example: 'Cognitive abilities develop with age.',
              ),
              VocabularyWord(
                id: 'psychology_4',
                english: 'behavioral',
                turkish: 'davranışsal',
                phonetic: '/bɪˈheɪvjərəl/',
                category: 'psychology',
                difficulty: DifficultyLevel.expert,
                hint: 'Davranış ile ilgili',
                example: 'Behavioral therapy is effective.',
              ),
              VocabularyWord(
                id: 'psychology_5',
                english: 'neuroplasticity',
                turkish: 'nöroplastisite',
                phonetic: '/ˌnʊroʊplæˈstɪsəti/',
                category: 'psychology',
                difficulty: DifficultyLevel.expert,
                hint: 'Beynin değişim yeteneği',
                example: 'Neuroplasticity allows brain adaptation.',
              ),
            ],
          ),
          GameExercise(
            id: 'exp_ex_5',
            levelId: 'expert_1',
            order: 5,
            title: 'Bilim ve Teknoloji',
            description: 'İleri bilimsel ve teknolojik terimler',
            difficulty: DifficultyLevel.expert,
            studyTimeSeconds: 55,
            recallTimeSeconds: 75,
            words: [
              VocabularyWord(
                id: 'science_1',
                english: 'quantum',
                turkish: 'kuantum',
                phonetic: '/ˈkwɑːntəm/',
                category: 'science',
                difficulty: DifficultyLevel.expert,
                hint: 'Atom altı fizik',
                example: 'Quantum mechanics is complex.',
              ),
              VocabularyWord(
                id: 'science_2',
                english: 'nanotechnology',
                turkish: 'nanoteknoloji',
                phonetic: '/ˌnænoʊtekˈnɑːlədʒi/',
                category: 'science',
                difficulty: DifficultyLevel.expert,
                hint: 'Moleküler düzeyde teknoloji',
                example: 'Nanotechnology has many applications.',
              ),
              VocabularyWord(
                id: 'science_3',
                english: 'biotechnology',
                turkish: 'biyoteknoloji',
                phonetic: '/ˌbaɪoʊtekˈnɑːlədʒi/',
                category: 'science',
                difficulty: DifficultyLevel.expert,
                hint: 'Canlı sistemler teknolojisi',
                example: 'Biotechnology advances medicine.',
              ),
              VocabularyWord(
                id: 'science_4',
                english: 'genomics',
                turkish: 'genomik',
                phonetic: '/dʒəˈnoʊmɪks/',
                category: 'science',
                difficulty: DifficultyLevel.expert,
                hint: 'Gen dizilimi bilimi',
                example: 'Genomics studies DNA sequences.',
              ),
              VocabularyWord(
                id: 'science_5',
                english: 'bioinformatics',
                turkish: 'biyoinformatik',
                phonetic: '/ˌbaɪoʊɪnfərˈmætɪks/',
                category: 'science',
                difficulty: DifficultyLevel.expert,
                hint: 'Biyolojik veri analizi',
                example: 'Bioinformatics processes biological data.',
              ),
            ],
          ),
          GameExercise(
            id: 'exp_ex_6',
            levelId: 'expert_1',
            order: 6,
            title: 'Ekonomi ve Finans',
            description: 'İleri ekonomik ve finansal kavramlar',
            difficulty: DifficultyLevel.expert,
            studyTimeSeconds: 55,
            recallTimeSeconds: 75,
            words: [
              VocabularyWord(
                id: 'economics_1',
                english: 'macroeconomics',
                turkish: 'makroekonomi',
                phonetic: '/ˌmækroʊɪkəˈnɑːmɪks/',
                category: 'economics',
                difficulty: DifficultyLevel.expert,
                hint: 'Büyük ölçekli ekonomi',
                example: 'Macroeconomics studies national economies.',
              ),
              VocabularyWord(
                id: 'economics_2',
                english: 'microeconomics',
                turkish: 'mikroekonomi',
                phonetic: '/ˌmaɪkroʊɪkəˈnɑːmɪks/',
                category: 'economics',
                difficulty: DifficultyLevel.expert,
                hint: 'Bireysel ekonomik davranış',
                example: 'Microeconomics analyzes individual choices.',
              ),
              VocabularyWord(
                id: 'economics_3',
                english: 'cryptocurrency',
                turkish: 'kripto para',
                phonetic: '/ˈkrɪptoʊˌkɜːrənsi/',
                category: 'economics',
                difficulty: DifficultyLevel.expert,
                hint: 'Dijital para birimi',
                example: 'Cryptocurrency uses blockchain technology.',
              ),
              VocabularyWord(
                id: 'economics_4',
                english: 'derivatives',
                turkish: 'türev ürünler',
                phonetic: '/dɪˈrɪvətɪvz/',
                category: 'economics',
                difficulty: DifficultyLevel.expert,
                hint: 'Finansal türev araçlar',
                example: 'Derivatives are complex financial instruments.',
              ),
              VocabularyWord(
                id: 'economics_5',
                english: 'arbitrage',
                turkish: 'arbitraj',
                phonetic: '/ˈɑːrbɪtrɑːʒ/',
                category: 'economics',
                difficulty: DifficultyLevel.expert,
                hint: 'Fiyat farkından kazanç',
                example: 'Arbitrage exploits price differences.',
              ),
            ],
          ),
        ],
      ),
    ];
  }
}
